import { useState, useEffect } from 'react';
import Header from './components/Header.jsx';
import Footer from './components/Footer.jsx';
import Home from './pages/Home.jsx';
import WatchLive from './pages/WatchLive.jsx';
import ExplorePage from './pages/ExplorePage.jsx';
import MarineLifePage from './pages/MarineLifePage.jsx';
import KidsClubPage from './pages/KidsClubPage.jsx';
import EducationPage from './pages/EducationPage.jsx';
import ConservationPage from './pages/ConservationPage.jsx';
import AboutPage from './pages/AboutPage.jsx';
import WaterParticlesCanvas from './components/WaterParticlesCanvas.jsx';
import useAmbientAudio from './hooks/useAmbientAudio.js';

export default function App() {
  const [page, setPage] = useState('home');
  const { isPlaying, toggleAudio } = useAmbientAudio();

  // Scroll to top on page change
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [page]);

  // Dynamic SEO Metadata updates based on active tab
  useEffect(() => {
    const seoData = {
      home: {
        title: 'SaltWaterCam | Live Underwater Camera Boynton Beach Inlet',
        desc: 'Watch a live 24/7 underwater camera near Lantana, Florida. Experience the Boynton Beach Inlet marine life, fish schooling, and ocean conditions live.'
      },
      watch: {
        title: 'Watch Live Underwater Feed | SaltWaterCam',
        desc: 'Tune into our live 24/7 underwater camera feed at Lantana dock. See Snook, Tarpon, and Green Sea Turtles in high definition day and night.'
      },
      'kids-club': {
        title: 'Kids Ocean Adventure & Missions | SaltWaterCam',
        desc: 'Fun educational ocean games, interactive quizzes, and marine conservation missions for kids. Earn shell rewards and learn about Florida wildlife.'
      },
      'marine-guide': {
        title: 'Florida Marine Life Guide & Directory | SaltWaterCam',
        desc: 'Identify local Florida fish and marine species including Snook, Tarpon, Goliath Grouper, and Green Sea Turtles. Learn fun facts and conservation status.'
      },
      community: {
        title: 'Community Sightings Board | SaltWaterCam',
        desc: 'Share your live camera fish sightings and connect with other ocean lovers. View daily sightings reports from the Boynton Beach Inlet area.'
      },
      'ai-features': {
        title: 'AI Computer Vision & LLM Telemetry | SaltWaterCam',
        desc: 'Explore live metrics from our edge YOLOv8 computer vision model and read natural language ecological summaries generated by our AI Biologist.'
      },
      rewards: {
        title: 'Ocean Rewards Catalog | SaltWaterCam',
        desc: 'Redeem your earned ocean shells for wallpapers, digital badges, and discounts at local Boynton Beach surf and gear shops.'
      },
      about: {
        title: 'About SaltWaterCam | Our Mission',
        desc: 'Learn about the history of the Lantana dock underwater camera, our green attraction light, and our partnerships in marine science education.'
      },
      contact: {
        title: 'Contact SaltWaterCam | Support',
        desc: 'Get in touch with the SaltWaterCam team for partnerships, feedback, or general questions about our live Boynton Beach camera feed.'
      }
    };

    const currentSeo = seoData[page] || seoData.home;
    document.title = currentSeo.title;
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', currentSeo.desc);
    }
  }, [page]);

  const renderPage = () => {
    switch (page) {
      case 'home':
        return <Home setPage={setPage} />;
      case 'watch':
        return <WatchLive />;
      case 'explore':
        return <ExplorePage />;
      case 'marine-life':
        return <MarineLifePage />;
      case 'kids-club':
        return <KidsClubPage />;
      case 'education':
        return <EducationPage setPage={setPage} />;
      case 'conservation':
        return <ConservationPage setPage={setPage} />;
      case 'about':
        return <AboutPage />;
      default:
        return <Home setPage={setPage} />;
    }
  };

  return (
    <div className={`app page-${page}`}>
      <WaterParticlesCanvas />
      <Header 
        page={page} 
        setPage={setPage} 
        isAudioPlaying={isPlaying} 
        onToggleAudio={toggleAudio} 
      />
      <main className="mainContent">
        {renderPage()}
      </main>
      <Footer setPage={setPage} />
    </div>
  );
}

